Wip day13
mtsochacki/advent-of-code pull request #14
Opened 2021-12-21 14:04 UTC by mtsochacki

Once again, parsing input is more than 50% of the code

2021-12-25 06:02 UTC, Lammatian requested changes
Not much logic to be corrected, mostly naming and the use of structures.

2021-12-25 06:02 UTC, Lammatian commented on 2021/day13/day13.java
> +                            + " dots visible after the first fold");
Return a value

2021-12-25 06:02 UTC, Lammatian commented on 2021/day13/day13.java
> +        System.out.print(String.format("%c[%d;%dH", 0x1B, 8, 0));
that's some magic that I'll allow. I guess here it's not really possible to return a value easily, but I would still stick with returning a value in `part1`

2022-01-04 11:57 UTC, mtsochacki commented on 2021/day13/day13.java
> +        output.addAll(set);
I replaced all ArrayList with Set because order never matters and it's not like we ever care about the duplicates

2022-01-04 16:31 UTC, Lammatian requested changes
Not sure about the hashCode, will get back to that later. The rest basically just naming

2022-01-04 16:31 UTC, Lammatian commented on 2021/day13/day13.java
> +    public enum Dimension {
In hindsight, `Axis` is a better name :D

2022-01-04 16:31 UTC, Lammatian commented on 2021/day13/day13.java
> +                instructions.add(instruction);
`instruction` -> `fold`

2022-01-04 16:31 UTC, Lammatian commented on 2021/day13/day13.java
> +        ArrayList<Fold> instructions = new ArrayList<>();
`instructions` -> `folds`

2022-01-04 16:31 UTC, Lammatian commented on 2021/day13/day13.java
> +                }
According to the description 'dots will never appear exactly on a fold line', so I guess you can just use `else` instead of `else if`

2022-01-04 16:31 UTC, Lammatian commented on 2021/day13/day13.java
> +                }
same as above

2022-01-05 09:41 UTC, Lammatian requested changes
One last renaming!

2022-01-05 12:21 UTC, merged