Day17 is finally here
mtsochacki/advent-of-code pull request #24
Opened 2022-01-21 15:26 UTC by mtsochacki

2022-01-21 18:35 UTC, Lammatian requested changes
This one's tough - a lot of the code repeats itself, but on the other hand I don't see one best way to make it DRY. I mentioned one possibility in one comment, another would maybe be a `Simulator` class with a method `simulate(Tuple2D point, Tuple2D velocity, borders2D)` with two subclasses: `YSimulator` and `XSimulator` that would have their own versions of `simulate(Tuple1D point, Tuple1D velocity, borders1D)`. `Tuple2D` and `Tuple1D` could be implementations of a `Tuple` base class.

2022-01-21 18:35 UTC, Lammatian commented on 2021/day17/day17.java
> +        }
I guess this is the reason why you have all the functions above even though they're basically all the same logic with minor differences. Maybe you could write just one function with additional arguments `boolean checkX, boolean checkY` that would do the calculations only for the axes that have this `boolean`s set to `true`? I don't exactly know how to make this work and be nice, but I just don't like the repetition.

2022-01-22 15:50 UTC, mtsochacki commented on 2021/day17/day17.java
> +            String[] coordinatesY = newLine[1].split("=")[1].split("\\..");
I WOULD BE IN TROUBLE

2022-01-22 15:52 UTC, mtsochacki commented on 2021/day17/day17.java
> +            }
It was really weird. Original version was even more weird.
I rewrote it to 5 lines of not weird methods now :D

2022-06-04 17:16 UTC, mtsochacki commented
I wasn't able to resolve everything, but I will merge it for now and have another look later

2022-06-04 17:16 UTC, merged