Day20
mtsochacki/advent-of-code pull request #25
Opened 2022-01-26 18:33 UTC by mtsochacki

2022-02-06 14:41 UTC, Lammatian requested changes
Quite a few corrections. Still can't get over `int var`. As discussed in DMs, consider adjusting the algorithm altogether - either by modifying the 'surrounding' to do it all at first or by surrounding after each step, but with correct type of pixel.

2022-02-06 14:41 UTC, Lammatian commented on 2021/day20/day20.java
> +        newImage.add(new ArrayList<>());
This should be replaced with `new ArrayList<>(Collections.nCopies(image.get(0).size() + 2), '.')`

2022-02-06 14:41 UTC, Lammatian commented on 2021/day20/day20.java
> +        }
This should be replaced with `new ArrayList<>(Collections.nCopies(image.get(0).size() + 2), '.')` (along with line 37)

2022-02-06 14:41 UTC, Lammatian commented on 2021/day20/day20.java
> +    public static int getIndex(ArrayList<ArrayList<Character>> image, int x, int y) {
Don't really like the naming. Maybe `determineOutputPixelIndex`?

2022-02-06 14:41 UTC, Lammatian commented on 2021/day20/day20.java
> +    public static int countPixels(int steps) {
`countPixels` -> `countLightPixels`

2022-02-06 14:41 UTC, Lammatian commented on 2021/day20/day20.java
> +    public static ArrayList<ArrayList<Character>> surroundWithDots(ArrayList<ArrayList<Character>> image) {
This smells like a (theoretically) great place to use linked lists - you keep on adding things at the beginning and at the end. However, do note that linked lists may not be faster than dynamic arrays in practice, even if they are in theory - read up on cache locality if you're interested in this.

On the other hand, you do need the indices when you do the checking of each pixel, so it's difficult to tell which approach is faster. How about some small benchmarking again?

2022-02-06 14:41 UTC, Lammatian commented on 2021/day20/day20.java
> +        int var = steps * 2;
I almost threw up (just use `2 * steps` in the for loop condition if you're already at this arcane solution)

2022-02-06 14:41 UTC, Lammatian commented on 2021/day20/day20.java
> +        for (int i = 0; i < var; i++) {
You can add `2 * steps + 1` 'border lines' at the beginning of the algorithm and then not worry about adding more later. Thus line 80 is spurious if you add one more line here. Also this should speed things up every so slightly.

2022-02-06 14:41 UTC, Lammatian commented on 2021/day20/day20.java
> +            image = surroundWithDots(image);
Unnecessary per earlier comment

2022-02-06 14:41 UTC, Lammatian commented on 2021/day20/day20.java
> +            }
You don't need to initialize `tmpImage` with `image`, you can just make an empty array of arrays of appropriate size.

2022-02-06 14:41 UTC, Lammatian commented on 2021/day20/day20.java
> +                    tmpImage.get(y).set(x, algorithm.charAt(getIndex(image, x, y)));
the `algorithm.charAt(getIndex(image, x, y))` could be a separate function `getOutputPixel`

2022-06-04 17:56 UTC, mtsochacki commented
Lot's of things to change, but I am merging for now

2022-06-04 17:56 UTC, merged